### ISSUE TITLE
[Submission]: test/non-existing-extension

### ISSUE THREAD

**Issue by felipecruz91** [benja-M-1/github-experiment#43]
### Docker Hub repository name

test/non-existing-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
:x: There was a problem during the validation job.

Someone from the @docker/extensions will have to take a look at this issue.
We will let you know in this issue when it is fixed.

---
See [action]({{ .workflow_url }}) for more details.
